spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://ec2-54-161-58-21.compute-1.amazonaws.com:5432/d5ks27pvda387e?user=seepstqppfanqb&password=71a1524c17e7ff7ee314ba5c3ab6af157039104b1fa5542f05aa67c52283efed"
#    url: "postgres://seepstqppfanqb:71a1524c17e7ff7ee314ba5c3ab6af157039104b1fa5542f05aa67c52283efed@ec2-54-161-58-21.compute-1.amazonaws.com:5432/d5ks27pvda387e"

    username: "seepstqppfanqb"
    password: "71a1524c17e7ff7ee314ba5c3ab6af157039104b1fa5542f05aa67c52283efed"
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 8000